### ISSUE TITLE
EOF marker absent

### ISSUE THREAD

**Issue by roskamsh** [PeeperLab/XenofilteR#6] opened 2019-05-14 18:50 UTC
Hello,

Thank you so much for creating this package, with very informative instructions!

I am currently using your software XenofilteR to filter out mm10 reads from contaminated hg38-mm10 samples, but find that when I try to view the filtered bam file through samtools, it throws me an error: 
```[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.```

I also get a similar error when I try to count through htseq and obtain gene counts:
```Error occured when reading beginning of SAM/BAM file. no BGZF EOF marker; file may be truncated```

However, when I ran XenofilteR, it did not report any errors. Below is the XenofilteR.log file for one of my samples. 
[XenofilteR.log](https://github.com/PeeperLab/XenofilteR/files/3179328/XenofilteR.log)

Is there an easy way to fix this error? Please let me know if you need any other information.

**Comment by PeeperLab2** [comment] 2019-05-15 18:53
Dear Breeshey,

I have checked my recent bam files that ran through XenofilteR but I do not have the EOF marker error. I also checked in some samples that were sequenced very deep.
So I cannot reproduce the error nor have I encountered it before.

A few questions that might help us solve your issue:
- If you run again, does the same error occur?
- What type of machine are you running on and how much Ram memory do you have available?
Samples with a high percentage of mouse reads generally need a bit more GBs.
- Since you used v1.6 I expected at the end of the log file more data regarding the versions of the packages etc. The log file ends after having calculated which reads are from human and which are not. The step after that is writing these reads to the new bam file. Is it possible that the machine was stopped for some reason or the connection to the disc was interrupted?

In addition:
- Could you check the end of the bam file to see whether all sequence reads are filtered? The bam is coordinated sorted so you know what the last reads should be. If everything is present you can at least continue with the data.

I am sorry I do not have a simple answer for you. If you could check the points above and let me know the answers that would be great. Hopefully we can solve it this way.
If we cannot figure it out it is always a possibility to share the bam file with me and see if I can reproduce the error. But this will depend on whether you are allowed to share this or not.

Kind regards, Oscar



On 14 May 2019, at 20:50, Breeshey Roskams-Hieter <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I am using your software XenofilteR, but find that when I try to view through samtools, it throws me an error:
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.

I also get a similar error when I try to count through htseq and obtain gene counts:

  no BGZF EOF marker; file may be truncated```

However, when I ran XenofilteR, it did not report any errors. Below is the XenofilteR.log file for one of my samples.
[XenofilteR.log](https://github.com/PeeperLab/XenofilteR/files/3179328/XenofilteR.log)

Is there an easy way to fix this error? Please let me know if you need any other information.

**Comment by roskamsh** [comment] 2019-05-15 19:52
Dear Oscar,

Thank you so much for getting back to me!

All of my XenofilteR.log files terminate after reporting the number of reads that were filtered out (same as the file uploaded on the issue). If there is supposed to be more information after that, maybe they did not complete properly. When I ran these, I did not terminate the session until hours after I got the message that those reads had been filtered out, so I am not too sure why it would have prematurely cancelled the job in that case.

I am running all of these on the OHSU cluster, starting a screen session and then launching an interactive session (requesting 1 CPU) and placing myself on a compute node. Once I am on this compute node, I activate my conda environment with the required dependencies ("Rsamtools", "GenomicAlignments", "BiocParallel", "futile.logger"), enter an R session on my terminal, and run the following code:


library("XenofilteR")



graftBam <- “samples/star_graft/S1_bam/Aligned.sortedByCoord.out.bam”

hostBam <- “samples/star_host/S1_bam/Aligned.sortedByCoord.out.bam”

sampname <- gsub("_bam", "", unlist(strsplit(graftBam,"/"))[3])

outDir <- paste("samples", "xeno", sampname, sep="/")



sample.list <- as.data.frame(cbind(graftBam, hostBam))

bp.param <- SnowParam(workers = 1, type = "SOCK")



dir.create(outDir, recursive = TRUE)

XenofilteR(sample.list, destination.folder = outDir, bp.param = bp.param)

All of these samples do have high mouse contamination (I know this for a fact), so maybe this is contributing to the error. Should I be requesting more CPUs when placing myself on a compute node? Is there an issue with requesting resources prior to launching R, and then passing in the bp.param again?

All of my samples did write to a new bam file, named “Aligned.sortedByCoord.out_Filtered.bam” (which, in combination with the log file, led me to believe they were completed), yet upon moving forward with these is how I got the error outlined in my issue on github.

I have looked at the end of the pre and post-filtered graft bam files, and there does seem to be a discrepancy in the reads that have been filtered. Below are my results:

Pre-filtered graft bam file:
samtools view Aligned.sortedByCoord.out.bam | tail
NS500681:342:H5VMJBGXB:3:22402:19649:4942       0       chrM    16513   255     57M18S  *       0       0       TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC      AAAAAEEEEEEEEEEEEEEEEEEEEAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEAEEEE<EE      NM:i:1
NS500681:342:H5VMJBGXB:3:23502:12700:16008      0       chrM    16513   255     57M18S  *       0       0       TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC      AAAA/EEEEEEE6EEEEEEEEEEEEA/AEEEEEE<E<AAEAEEEEEEEEAAEEEEAEEEEAEEEEEEEEEEEAEA      NM:i:1
NS500681:342:H5VMJBGXB:4:12510:24241:10406      0       chrM    16513   255     57M18S  *       0       0       TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC      AAAAAEEEEEEEAAEEEEAEEE/EEAAE/EEEEEEEE/EEEEE/EEEEEEE<AEEE/<EEAA<AEAE6EEEAE6A      NM:i:1
NS500681:342:H5VMJBGXB:4:13611:13808:2162       0       chrM    16513   255     57M18S  *       0       0       TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC      AAAAAEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEAEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEE      NM:i:1
NS500681:342:H5VMJBGXB:4:22508:11060:9572       0       chrM    16513   255     57M18S  *       0       0       TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC      AAAAAEAEEEAEEE/EEEEEEEAE<EE<EEEEEA/AAEEEEEEEEEEEEEEEE/E</EEAEE<AAAEAAE<<AEA      NM:i:1
NS500681:342:H5VMJBGXB:4:23606:10915:9752       0       chrM    16513   255     57M18S  *       0       0       TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC      AAAAAEEEEEEEEEEEEEEEEEEEAEEEEEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEE<EA      NM:i:1
NS500681:342:H5VMJBGXB:3:21612:16546:9853       16      chrM    16514   255     56M19S  *       0       0       CAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTACCACCC      AEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEAAAAA      NM:i:1
NS500681:342:H5VMJBGXB:4:12607:14275:15228      16      chrM    16514   255     56M19S  *       0       0       CAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTACCACCC      EE<AEAA/E<EEE</E/EEEEAEEEEA/AEEEEEEEEEEEEEEE/EEEEE/EEEEEEEAEEEEAEEEEEEA/AA/      NM:i:1
NS500681:342:H5VMJBGXB:2:11205:26279:14086      16      chrM    16516   3       54M21S  *       0       0       GGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCAG      6AAEEEEEEEEEEEEEEEE<E<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA      NM:i:1
NS500681:342:H5VMJBGXB:1:21203:2840:9291        272     chrM    16520   3       1S50M24S        *       0       0CCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCAACTC     E/AEEE</EEEEE/AEEEEA<EAE66A/E66EEEE66EEAEEEE/EE/EEEE(/ho((/h((/h

Post-filtered bam file:
samtools view Aligned.sortedByCoord.out_Filtered.bam | tail
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[E::inflate_block] inflate failed: progress temporarily not possible, or in() / out() returned an error
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[main_samview] truncated file.
NS500681:342:H5VMJBGXB:1:21111:23735:2127       0       chr2    213039664       255     2S73M   *       0       0       ATTTGCTCCAAAGTTATGTGATACAGATAACTAATTTTACAAAGTAGTTATTTTTAAGTGATATACACAAATAAAAAAAAEEEEE/EEEEE6EEEEEAEEEEEEEA//AEEEEA/E/EAEEEE/EE<EAEE6E/AEEEE/E/EEE<EAEA      NM:i:1
NS500681:342:H5VMJBGXB:1:23106:17525:2939       0       chr2    213039665       255     75M     *       0       0       TACTCCAAAGTTATGTGATACAGATAACTAATTTTACAAAGTAGTTATTTTTAAGTGATATACACAAATAAATAAAAAAAEEEEAEEAEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEAEEE<AEEEEEEEE<EEEEEEEEE      NM:i:0
NS500681:342:H5VMJBGXB:4:12611:26516:14217      0       chr2    213039665       255     75M     *       0       0       TACTCCAAAGTTATGTGATACAGATAACTAATTTTACAAAGTAGTTATTTTTAAGTGATATACACAAATAAATAAAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEAE<EEEEEEEEAA      NM:i:0
NS500681:342:H5VMJBGXB:3:13610:13833:6533       0       chr2    213039757       255     75M     *       0       0       TGCTGGTTCAATTGAAAGCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEAAEEEEEEEEEEAEEEEEEEEEE      NM:i:0
NS500681:342:H5VMJBGXB:4:12612:21599:14898      0       chr2    213039757       255     74M     *       0       0       TGCTGGTTCAATTGAAAGCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTC A6AAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEAAEEEEEEEE6EEEAEEEEEEEAE       NM:i:0
NS500681:342:H5VMJBGXB:4:21607:6827:15293       0       chr2    213039757       255     75M     *       0       0       TGCTGGTTCAATTGAAAGCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEAEEEEEEEEEEAEEEEEE      NM:i:0
NS500681:342:H5VMJBGXB:1:11203:14678:18395      0       chr2    213039774       255     75M     *       0       0       GCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTTAAAATGAGGATGAACAAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEAEAEEEEEEEEEEEEEEE      NM:i:0
NS500681:342:H5VMJBGXB:1:13102:26289:4433       0       chr2    213039774       255     75M     *       0       0       GCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTTAAAATGAGGATGAACAAAAAAE6EEEEEEEEEEEE/EEEEEEEEEEAE<EEAEEEEAEEEEEEEEEEAEAE<EEEEEEEEEEEEEEEAAEA      NM:i:0
NS500681:342:H5VMJBGXB:3:12509:2512:13204       0       chr2    213040056       255     1S74M   *       0       0       ATCCGTTTTTGAGCAATACATAATTTTCATAGTAATCTGAACCAGTATAATTCTTAGCCAAAATTGAATTTTTCAAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEAEEAEEEEEEEEEEAAAEEAEEEAEEEEEEEE      NM:i:0
NS500681:342:H5VMJBGXB:3:23608:14261:15701      0       chr2    213040255       255     66M     *       0       0       TTTTGGTATAAATTATTTTGTCATCCAGGTATTAAGGCTAGCAACATTAGTTATTTTCTCCTCATT      AAAAAEE6E666EE//EAEEEEE//<//EE/EEEE66EE66E//EEEEE/E/EE/EA/EA/E/EEE  NM:i:2

I can re-run my samples, to see if the issue persists. Please let me know if there is anything I should change about how I am running them, given what I have told you above, that may help to resolve the issue.

Please let me know any other information you might need. I would also be interested to hear your workflow for how you implement these on the cluster, because maybe my approach is not the best. I would also be interested in sharing a bam file with you to see if you have the same issue as me.

Let me know as soon as you can, and thank you for your time!
Best,
Breeshey

**Comment by roskamsh** [comment] 2019-05-16 22:05
Hello Oscar!

Just sending a quick follow-up email to see if there is any information I can provide you with that will help us figure out why my samples won’t complete properly! I am very interested to see your exact workflow and how you submit these jobs on a cluster. I am also interested in sharing one of my files with you, which might give you better insight on why they won’t complete. Let me know!

Thanks,
Breeshey

**Comment by PeeperLab2** [comment] 2019-05-17 07:05
Dear Breeshey,

From your files it is clear the filtered bam is somehow truncated. Since the classification in XenofilteR works (Log has % filtered) it must be with the actual filter step where we use FilterBam from the Rsamtools package to make the new filtered bam file.
The easiest way forward would to share a file so I can run it on my system and see whether I can reproduce the error. If I can reproduce it I can probably find out what goes wrong.

Is there anyway you can share one set of files with me (human and mouse mapped)?

Best Oscar


On 15 May 2019, at 21:52, Breeshey Roskams-Hieter <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Oscar,

Thank you so much for getting back to me!

All of my XenofilteR.log files terminate after reporting the number of reads that were filtered out (same as the file uploaded on the issue). If there is supposed to be more information after that, maybe they did not complete properly. When I ran these, I did not terminate the session until hours after I got the message that those reads had been filtered out, so I am not too sure why it would have prematurely cancelled the job in that case.

I am running all of these on the OHSU cluster, starting a screen session and then launching an interactive session (requesting 1 CPU) and placing myself on a compute node. Once I am on this compute node, I activate my conda environment with the required dependencies ("Rsamtools", "GenomicAlignments", "BiocParallel", "futile.logger"), enter an R session on my terminal, and run the following code:


library("XenofilteR")



graftBam <- “samples/star_graft/S1_bam/Aligned.sortedByCoord.out.bam”

hostBam <- “samples/star_host/S1_bam/Aligned.sortedByCoord.out.bam”

sampname <- gsub("_bam", "", unlist(strsplit(graftBam,"/"))[3])

outDir <- paste("samples", "xeno", sampname, sep="/")



sample.list <- as.data.frame(cbind(graftBam, hostBam))

bp.param <- SnowParam(workers = 1, type = "SOCK")



dir.create(outDir, recursive = TRUE)

XenofilteR(sample.list, destination.folder = outDir, bp.param = bp.param)

All of these samples do have high mouse contamination (I know this for a fact), so maybe this is contributing to the error. Should I be requesting more CPUs when placing myself on a compute node? Is there an issue with requesting resources prior to launching R, and then passing in the bp.param again?

All of my samples did write to a new bam file, named “Aligned.sortedByCoord.out_Filtered.bam” (which, in combination with the log file, led me to believe they were completed), yet upon moving forward with these is how I got the error outlined in my issue on github.

I have looked at the end of the pre and post-filtered graft bam files, and there does seem to be a discrepancy in the reads that have been filtered. Below are my results:

Pre-filtered graft bam file:
samtools view Aligned.sortedByCoord.out.bam | tail
NS500681:342:H5VMJBGXB:3:22402:19649:4942 0 chrM 16513 255 57M18S * 0 0 TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC AAAAAEEEEEEEEEEEEEEEEEEEEAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEAEEEE<EE NM:i:1
NS500681:342:H5VMJBGXB:3:23502:12700:16008 0 chrM 16513 255 57M18S * 0 0 TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC AAAA/EEEEEEE6EEEEEEEEEEEEA/AEEEEEE<E<AAEAEEEEEEEEAAEEEEAEEEEAEEEEEEEEEEEAEA NM:i:1
NS500681:342:H5VMJBGXB:4:12510:24241:10406 0 chrM 16513 255 57M18S * 0 0 TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC AAAAAEEEEEEEAAEEEEAEEE/EEAAE/EEEEEEEE/EEEEE/EEEEEEE<AEEE/<EEAA<AEAE6EEEAE6A NM:i:1
NS500681:342:H5VMJBGXB:4:13611:13808:2162 0 chrM 16513 255 57M18S * 0 0 TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC AAAAAEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEAEEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEE NM:i:1
NS500681:342:H5VMJBGXB:4:22508:11060:9572 0 chrM 16513 255 57M18S * 0 0 TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC AAAAAEAEEEAEEE/EEEEEEEAE<EE<EEEEEA/AAEEEEEEEEEEEEEEEE/E</EEAEE<AAAEAAE<<AEA NM:i:1
NS500681:342:H5VMJBGXB:4:23606:10915:9752 0 chrM 16513 255 57M18S * 0 0 TCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACC AAAAAEEEEEEEEEEEEEEEEEEEAEEEEEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEE<EA NM:i:1
NS500681:342:H5VMJBGXB:3:21612:16546:9853 16 chrM 16514 255 56M19S * 0 0 CAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTACCACCC AEEEEEEEEEEEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEAAAAA NM:i:1
NS500681:342:H5VMJBGXB:4:12607:14275:15228 16 chrM 16514 255 56M19S * 0 0 CAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTACCACCC EE<AEAA/E<EEE</E/EEEEAEEEEA/AEEEEEEEEEEEEEEE/EEEEE/EEEEEEEAEEEEAEEEEEEA/AA/ NM:i:1
NS500681:342:H5VMJBGXB:2:11205:26279:14086 16 chrM 16516 3 54M21S * 0 0 GGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCAG 6AAEEEEEEEEEEEEEEEE<E<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA NM:i:1
NS500681:342:H5VMJBGXB:1:21203:2840:9291 272 chrM 16520 3 1S50M24S * 0 0CCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCAACTC E/AEEE</EEEEE/AEEEEA<EAE66A/E66EEEE66EEAEEEE/EE/EEEE(/ho((/h((/h

Post-filtered bam file:
samtools view Aligned.sortedByCoord.out_Filtered.bam | tail
[W::bam_hdr_read] EOF marker is absent. The input is probably truncated.
[E::inflate_block] inflate failed: progress temporarily not possible, or in() / out() returned an error
[E::bgzf_read_block] inflate_block error -1
[E::bgzf_read] bgzf_read_block error -1 after 0 of 4 bytes
[main_samview] truncated file.
NS500681:342:H5VMJBGXB:1:21111:23735:2127 0 chr2 213039664 255 2S73M * 0 0 ATTTGCTCCAAAGTTATGTGATACAGATAACTAATTTTACAAAGTAGTTATTTTTAAGTGATATACACAAATAAAAAAAAEEEEE/EEEEE6EEEEEAEEEEEEEA//AEEEEA/E/EAEEEE/EE<EAEE6E/AEEEE/E/EEE<EAEA NM:i:1
NS500681:342:H5VMJBGXB:1:23106:17525:2939 0 chr2 213039665 255 75M * 0 0 TACTCCAAAGTTATGTGATACAGATAACTAATTTTACAAAGTAGTTATTTTTAAGTGATATACACAAATAAATAAAAAAAEEEEAEEAEAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEAEEE<AEEEEEEEE<EEEEEEEEE NM:i:0
NS500681:342:H5VMJBGXB:4:12611:26516:14217 0 chr2 213039665 255 75M * 0 0 TACTCCAAAGTTATGTGATACAGATAACTAATTTTACAAAGTAGTTATTTTTAAGTGATATACACAAATAAATAAAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEAE<EEEEEEEEAA NM:i:0
NS500681:342:H5VMJBGXB:3:13610:13833:6533 0 chr2 213039757 255 75M * 0 0 TGCTGGTTCAATTGAAAGCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEAAEEEEEEEEEEAEEEEEEEEEE NM:i:0
NS500681:342:H5VMJBGXB:4:12612:21599:14898 0 chr2 213039757 255 74M * 0 0 TGCTGGTTCAATTGAAAGCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTC A6AAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEAAEEEEEEEE6EEEAEEEEEEEAE NM:i:0
NS500681:342:H5VMJBGXB:4:21607:6827:15293 0 chr2 213039757 255 75M * 0 0 TGCTGGTTCAATTGAAAGCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEAEEEEEEEEEEAEEEEEE NM:i:0
NS500681:342:H5VMJBGXB:1:11203:14678:18395 0 chr2 213039774 255 75M * 0 0 GCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTTAAAATGAGGATGAACAAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEEEAEAEEEEEEEEEEEEEEE NM:i:0
NS500681:342:H5VMJBGXB:1:13102:26289:4433 0 chr2 213039774 255 75M * 0 0 GCTGAGGTTTTACTTAGAATTTAATAGCATTATTGAAAATATGAAATAATTATTTTCTTAAAATGAGGATGAACAAAAAAE6EEEEEEEEEEEE/EEEEEEEEEEAE<EEAEEEEAEEEEEEEEEEAEAE<EEEEEEEEEEEEEEEAAEA NM:i:0
NS500681:342:H5VMJBGXB:3:12509:2512:13204 0 chr2 213040056 255 1S74M * 0 0 ATCCGTTTTTGAGCAATACATAATTTTCATAGTAATCTGAACCAGTATAATTCTTAGCCAAAATTGAATTTTTCAAAAAAEEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEEEEEAEEAEEEEEEEEEEAAAEEAEEEAEEEEEEEE NM:i:0
NS500681:342:H5VMJBGXB:3:23608:14261:15701 0 chr2 213040255 255 66M * 0 0 TTTTGGTATAAATTATTTTGTCATCCAGGTATTAAGGCTAGCAACATTAGTTATTTTCTCCTCATT AAAAAEE6E666EE//EAEEEEE//<//EE/EEEE66EE66E//EEEEE/E/EE/EA/EA/E/EEE NM:i:2

I can re-run my samples, to see if the issue persists. Please let me know if there is anything I should change about how I am running them, given what I have told you above, that may help to resolve the issue.

Please let me know any other information you might need. I would also be interested to hear your workflow for how you implement these on the cluster, because maybe my approach is not the best. I would also be interested in sharing a bam file with you to see if you have the same issue as me.

Let me know as soon as you can, and thank you for your time!
Best,
Breeshey

**Comment by roskamsh** [comment] 2019-05-17 18:20
Dear Oscar,

I have emailed you (o.krijgsman@nki.nl) with the link to download the bam files. Please let me know if there is any other information you need.

Best,
Breeshey

**Comment by PeeperLab2** [comment] 2019-05-22 19:16
Dear Breeshey,

Thank you for sharing the bam files.
I ran XenofilteR on the bam on our system. Here it did run without any issues and finished the complete log file.
I also checked the last reads in the filtered bam file and these end with reads mapped to the mitochondria as expected. See also attachment.

I am really sorry that I cannot help you with your error. I suspect that it is something on your server that stops XenofilteR. Do you have to preallocate memory? If so, how much do you request? It might be that it runs into trouble there. Your file have a large percentage of mouse reads which requires more memory.

Hope you can find what is happening on your system that causes the error. Please let me know if I can be of any further assistance.

Kind regards, Oscar



[cid:2C6E921A-52B1-4DAB-9568-A518E52BF445@arnhem.chello.nl]




On 17 May 2019, at 20:21, Breeshey Roskams-Hieter <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Oscar,

I have emailed you (o.krijgsman@nki.nl<mailto:o.krijgsman@nki.nl><mailto:o.krijgsman@nki.nl>) with the link to download the bam files. Please let me know if there is any other information you need.

Best,
Breeshey

**Comment by roskamsh** [comment] 2019-05-22 19:22
Dear Oscar,

How long did it take (from start to finish) for the filtered bam files to be generated? I do have to preallocate memory, and was wondering if you have a suggestion for how much I should be allocating?
Please let me know when you can, thank you!

Best,
Breeshey

**Comment by PeeperLab2** [comment] 2019-05-22 19:37
Dear Breeshey,

It took 1 and a half hour on our machine.
I am not really sure how much would be needed. I have seen it go up to 60gb for some sample. Most need much less though.
So I possible I would preallocate over 60gb. But I do not know if that is feasible for you.

Best Oscar





On 22 May 2019, at 21:22, Breeshey Roskams-Hieter <notifications@github.com<mailto:notifications@github.com>> wrote:

Dear Oscar,

How long did it take (from start to finish) for the filtered bam files to be generated? I do have to preallocate memory, and was wondering if you have a suggestion for how much I should be allocating?
Please let me know when you can, thank you!

Best,
Breeshey

**Comment by roskamsh** [comment] 2019-05-22 20:58
Dear Oscar,

I re-allocated more resources per sample, and they have completed successfully! So it must have been a memory issue. Thank you so much for your helpful feedback!

Best,
Breeshey

**Closed as completed** 2021-07-12 07:07 UTC
